### ISSUE TITLE
Attempted to load class "TransferMsgDetails" from namespace "at\externet\eps_bank_transfer". Did you forget a "use" statement for another namespace?

### ISSUE THREAD

**Issue by Allyda** [hakito/PHP-Stuzza-EPS-BankTransfer#20]
For EPS integration in an online shop I installed this composer package. Unfortunately, the namespaces don't seem to load correctly.

**Code-Snippet:**  (autoloaded via composer)

```php
$transferMsgDetails = new \at\externet\eps_bank_transfer\TransferMsgDetails($responseUrl, $successUrl, $failUrl);
```

**Error:** 

```
Attempted to load class "TransferMsgDetails" from namespace "at\externet\eps_bank_transfer".
Did you forget a "use" statement for another namespace?
```
It doesn't find a single class from the given namespace.

For the sake of interest, I just installed the composer package and ran its unit tests.

**Output:**

```
Deprecated: The PSR-0 `Requests_...` class names in the Request library are deprecated. Switch to the PSR-4 `WpOrg\Requests\...` class names at your earliest convenience.
Fatal error: Declaration of at\externet\eps_bank_transfer\MockTransport::test() must be compatible with WpOrg\Requests\Transport::test($capabilities = Array)
```

Am I doing something wrong, or does this library just not work (anymore)?

**Comment by hakito** [comment]
It is working and actively used.
I suppose there is a problem with the autoloader.  Does the composer autoloader work for other packages? Which PHP version are you using?

**Comment by Allyda** [comment]
Thanks for your response.
I already tried `composer dump` - all my other composer library work well - and my project also uses the autoloading feature of composer.
I am using PHP 7.4.28 at the moment.

**Comment by hakito** [comment]
I guess the namespace is incorrectly converted to snake case and therefore it does not find the correct folder. I cannot look into this  for the next three weeks (boat trip). Maybe you can try if manual renaming of the folder would make it work?!?

**Comment by Allyda** [comment]
I am not sure what to rename. 🤔
In my opinion everything should be correct.

**Comment by Allyda** [comment]
I've gotten a little further now, but I receive the following Error now:

```
007SO: Fehler im XML-Stream:javax.xml.bind.UnmarshalException - with linked exception: [org.xml.sax.SAXParseException: cvc-elt.1: Cannot find the declaration of element 'epsp:EpsProtocolDetails'.]
XML does not validate against XSD. Element '{http://www.stuzza.at/namespaces/eps/protocol/2013/02}EpsProtocolDetails': No matching global declaration available for the validation root. /var/www/html/custom/plugins/EPS/vendor/hakito/php-stuzza-eps-banktransfer/src/XmlValidator.php38
```

**Comment by hakito** [comment]
The implementation validates the XMLs against the XSDs during server communication. Can you check that the file _XSD\EPSProtocol-V26.xsd_ can be read by the PHP process?

**Comment by Allyda** [comment]
File exists and is readable (by the running php process)

**Comment by hakito** [comment]
FYI I just released v2.0.1 wich addresses a dependency issue.

**Comment by Allyda** [comment]
I already updated to the latest version, but the error message is still the same.

```
XML does not validate against XSD. Element '{http://www.stuzza.at/namespaces/eps/protocol/2013/02}EpsProtocolDetails': No matching global declaration available for the validation root. /var/www/html/custom/plugins/EPS/vendor/hakito/php-stuzza-eps-banktransfer/src/XmlValidator.php38
```

As you can see in my code - I am not using `ValidateBankList` - and the snippet is more or less the same then your [sample](https://github.com/hakito/PHP-Stuzza-EPS-BankTransfer/blob/master/samples/eps_start.php) - I just replaced the parameters. 

```php
        $config = $this->config->getConfig();
        $targetUrl = $config['api_url'];

        $customer = $order->getOrderCustomer();
        $billingAddress = $order->getBillingAddress();
        // $country = $billingAddress->getCountry();

        $responseUrl = htmlspecialchars($returnUrl . '&status=confirm');
        $successUrl = htmlspecialchars($returnUrl . '&status=success');
        $failUrl = htmlspecialchars($returnUrl . '&status=error');

        $transferMsgDetails = new TransferMsgDetails($responseUrl, $successUrl, $failUrl);

        $orderTotal = $order->getAmountTotal() * 100;

        try {
            $transferInitiatorDetails = new TransferInitiatorDetails(
                $config['user_id'],
                $config['pin'],
                $config['bic'],
                $customer->getFirstName() . ' ' . $customer->getLastName(), 
                $config['iban'],
                $order->getOrderNumber(),
                (int)$orderTotal,
                $transferMsgDetails
            );

            $transferInitiatorDetails->RemittanceIdentifier = $order->getOrderNumber();
            $transferInitiatorDetails->SetExpirationMinutes(60);

            //Send TransferInitiatorDetails to Scheme Operator
            $soCommunicator = new SoCommunicator(!$config['is_production']);
            $plain = $soCommunicator->SendTransferInitiatorDetails($transferInitiatorDetails, $targetUrl);

            $xml = new SimpleXMLElement($plain);
            $soAnswer = $xml->children(\at\externet\eps_bank_transfer\XMLNS_epsp);

            $errorDetails = $soAnswer->BankResponseDetails->ErrorDetails;

            if ($errorDetails->ErrorCode != '000') {
                throw new \Exception(print_r($errorDetails, true));
            } else {
                $redirectUrl = $soAnswer->BankResponseDetails->ClientRedirectUrl->__toString();
                return $redirectUrl;
            }
        } catch (\Exception $e) {
            print_r($e->getMessage());
            print_r($e->getFile());
            print_r($e->getLine());
            die();
        }
```

**Comment by hakito** [comment]
> Can you post the call stack?

**Comment by Allyda** [comment]
```
#0  at\externet\eps_bank_transfer\XmlValidator::ValidateXml(007SO: Fehler im XML-Stream:javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException: cvc-elt.1: Cannot find the declaration of element 'epsp:EpsProtocolDetails'.], /var/www/html/custom/plugins/EPS/vendor/hakito/php-stuzza-eps-banktransfer/XSD/EPSProtocol-V26.xsd) called at [/var/www/html/custom/plugins/EPS/vendor/hakito/php-stuzza-eps-banktransfer/src/XmlValidator.php:14]
#1  at\externet\eps_bank_transfer\XmlValidator::ValidateEpsProtocol(007SO: Fehler im XML-Stream:javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException: cvc-elt.1: Cannot find the declaration of element 'epsp:EpsProtocolDetails'.]) called at [/var/www/html/custom/plugins/EPS/vendor/hakito/php-stuzza-eps-banktransfer/src/SoCommunicator.php:134]
#2  at\externet\eps_bank_transfer\SoCommunicator->SendTransferInitiatorDetails(at\externet\eps_bank_transfer\TransferInitiatorDetails Object ([UserId] => XXX,[Secret] => XXX,[Date] => 2022-06-30,[BfiBicIdentifier] => XXX,[BeneficiaryNameAddressText] => XXX,[BeneficiaryAccountIdentifier] => XXX,[ReferenceIdentifier] => XXX,[UnstructuredRemittanceIdentifier] => ,[RemittanceIdentifier] => XXX,[ExpirationTime] => 2022-06-30T10:45:12+00:00,[InstructedAmount] => 19.98,[AmountCurrencyIdentifier] => EUR,[WebshopArticles] => Array (),[TransferMsgDetails] => at\externet\eps_bank_transfer\TransferMsgDetails Object ([ConfirmationUrl] => http://localhost/payment/finalize&status=confirm,[TransactionOkUrl] => http://localhost/payment/finalize&status=success,[TransactionNokUrl] => http://localhost/payment/finalize&status=error,[TargetWindowOk] => ,[TargetWindowNok] => ),[OrderingCustomerOfiIdentifier] => ), https://routing.eps.or.at/appl/epsSO-test/transinit/eps/v2_5) called at [/var/www/html/custom/plugins/EPS/src/Library/EPS/SmartCheckoutHelper.php:69]
```

**Comment by hakito** [comment]
According to the stack trace it seems the return value from the server is not a valid XML. You could try to debug the return value from the server by intercepting the response at:

https://github.com/hakito/PHP-Stuzza-EPS-BankTransfer/blob/003e8f8982e1b942bd3167804abca0c13e7a069b/src/SoCommunicator.php#L134

My first guess is that the credentials are invalid.
